### ISSUE TITLE
Could you provide the matlab interface to metis function  'NodeBisect'?

### ISSUE THREAD

**Issue by winsonwoods** [YingzhouLi/metismex#1]
Mr.YingzhouLi,
Thank you for your sharing your code .I have compile successfully in ubuntu-64bit with matlab 2016b. However, I still can't use the 'NodeBisect' function, and I have to use the function to carry out some opt.
Please provide me the metismex.c file with 'NodeBisect' function?.
Thank you in advance!
Yours sincerely,
Winson Woods.
OCt-10 2016.

**Comment by YingzhouLi** [comment]
Hi

Could you be more precise about the 'NodeBisect' function? I did not find it in the metis.

Best,
Yingzhou

**Comment by YingzhouLi** [comment]
Please take a look at 
https://github.com/YingzhouLi/metismex/blob/master/test/test.m#L14

I am not sure if this is the functionality you need.

**Comment by YingzhouLi** [comment]
Please let me know if your issue is addressed or not. If your issue is addressed or you do not reply for a week, I will close this issue.
