### ISSUE TITLE
Unrecognized function or variable 'METIS_SepPartition_mex'.

### ISSUE THREAD

**Issue by janiopt** [YingzhouLi/metismex#2]
Good Morning,

I was running your implementation but I was unable to run the examples. There is an error with one of the functions, as it does not have a .m version of it.

There is a file METIS_SepPartition_mex.c but not METIS_SepPartition_mex.m.

How can I fix that?

![image](https://user-images.githubusercontent.com/67653156/86158877-bdb3d300-bb09-11ea-9efd-cba7ffea8bc3.png)

**Comment by YingzhouLi** [comment]
Did you ``make`` the code before you run?
I am referring to Step 3 Compile MetisMex in the ReadMe.

**Comment by janiopt** [comment]
Yes, I "make" first. I use Windows 10. 
![image](https://user-images.githubusercontent.com/67653156/86172486-b519c780-bb1e-11ea-98c0-3c199c65e382.png)

**Comment by janiopt** [comment]
I think it is the problem is when I run 'make', the mex files are not generated in buil/src. Are there instructions for windows?

**Comment by YingzhouLi** [comment]
I do not have support for windows in the beginning. Currently, I am testing MinGW-W64 as the option. Do you have WSL on your windows?

**Comment by janiopt** [comment]
I do not have WSL, but I will consider it and try to install and run the metis mex files.

**Comment by YingzhouLi** [comment]
WSL does not solve the problem. I will further test it and let you know.

**Comment by janiopt** [comment]
Ok, I do not so expert in these topics. Thanks, I will keep checking this post.

**Comment by YingzhouLi** [comment]
I have added the support for Windows users. Could you please install metismex following the instruction in [ReadME](https://github.com/YingzhouLi/metismex)? If you encountered any issue, please let me know.

**Comment by YingzhouLi** [comment]
@janiopt if you have tried the updated code and it works on your computer, I would like to close this issue.

**Comment by janiopt** [comment]
Good Afternoon. Thanks for your help, I was able to update the code. I will refer to the manual for understanding METIS.  If there is another resource for understanding,  it will be nice to know it.
