### ISSUE TITLE
make.m problem in win10 & MinGW64 compiler

### ISSUE THREAD

**Issue by lucreziamanieri** [YingzhouLi/metismex#3]
I am on a windows 10 with matlab r2020a and MinGW64. 
When I run "make.m" from the Windows PowerShell, the matlab command window shows the error: 

**"Error using mex
gcc: error: \-fexceptions: No such file or directory

Error in make (line 101)
            eval(['mex -largeArrayDims -lmetis '...-"**
![image](https://user-images.githubusercontent.com/49156603/100218269-d25b9200-2f14-11eb-9ed6-5d48517b2072.png)

**Comment by YingzhouLi** [comment]
Can you pull the newest version and give it a try?

**Comment by lucreziamanieri** [comment]
Thanks! I think it solved the previous issue, the error changed to:

![image](https://user-images.githubusercontent.com/49156603/100231333-27080880-2f27-11eb-8910-5925b6e8c54c.png)

**Comment by YingzhouLi** [comment]
How did you install metis library? It looks like that your metis library is not linked correctly.

**Comment by dani-agramonte** [comment]
I'd like to note that I had precisely the same issue, line by line. When I installed my metis library: [Command_History.txt](https://github.com/YingzhouLi/metismex/files/7560148/Command_History.txt)
![Screenshot 2021-11-18 002804](https://user-images.githubusercontent.com/74071056/142357275-8854f389-390b-4f0e-8c2c-8305e681ff9a.png)

The only change I made when installing metis is slightly altering the prompts to allow for the use of Visual Studio 2022.

I currently have MATLAB 2020b and am on Windows 10.

**Comment by YingzhouLi** [comment]
It looks your error is similar to "https://stackoverflow.com/questions/16623407/build-error-bad-reloc-address"
Could you please check the installation of the metis again? Especially the incompatibility between intel compiler and gnu compilers.
